name: Publish to Pages
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - name: Bundle scripts for production
        run: |
          rm -rf dist
          mkdir dist
          mkdir dist/public
          mkdir dist/private
          cp public.sh ./dist/public/index.html
          cp private.sh ./dist/private/index.html
      - name: Deploy public script
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: cpk-public
          directory: ./dist/public
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy private script
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: cpk-private
          directory: ./dist/private
          githubToken: ${{ secrets.GITHUB_TOKEN }}
